## Variables
@email = customer@sparta.com
@password = P@ssw0rd
@role = guest

### 유저 계정 등록
POST http://localhost:8080/accounts/join?role={{role}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 유저 로그인
POST http://localhost:8080/accounts/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
  client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 로그아웃
POST http://localhost:8080/accounts/logout
Authorization: Bearer {{accessToken}}

### 현재 사용자의 인증정보 확인
GET http://localhost:8080/accounts/me
Authorization: Bearer {{accessToken}}