## Variables
@email = staff@sparta.com
@password = P@ssw0rdSt@ff
@role = staff

### 스탭 계정 등록
POST http://localhost:8080/accounts/join?role={{role}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 스탭 로그인
POST http://localhost:8080/accounts/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
%}

### 현재 사용자의 인증정보 확인
GET http://localhost:8080/accounts/me
Authorization: Bearer {{accessToken}}

### 스탭 권한 로직
GET http://localhost:8080/staff/something
Authorization: Bearer {{accessToken}}

### 다른 권한의 엔드포인트 접근 - 어드민
GET http://localhost:8080/admin/something
Authorization: Bearer {{accessToken}}

### 다른 권한의 엔드포인트 접근 - 유저
GET http://localhost:8080/user/something
Authorization: Bearer {{accessToken}}

### 로그아웃
POST http://localhost:8080/accounts/logout
Authorization: Bearer {{accessToken}}
